name: Golang CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go_version: [1.17]
    steps:
      - name: checkout  
        uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }} 
      - name: go tests
        run: |
          echo "getting dependencies...".
          go get -v -u ./...
          echo "go test for ${{ matrix.os }} and version ${{ matrix.go_version }}".
          go test -v ./... -cover -race
          go build -v -o ${{ github.workspace }}/dist/maven-versions-prettify-${{ matrix.os }} main.go
          ls ${{ github.workspace }}/dist/
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: maven-versions-prettify-${{ matrix.os }}
          path: ${{ github.workspace }}/dist/**/*
          retention-days: 3